name: Build documentation
# on: workflow_call
on:
  push:
    branches:
      - '35-add-support-of-linux-platform-in-docs'
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  resolve_tag:
    name: Resolving release tag
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.get_last_release.outputs.TAG }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get previous stable release tag
        id: get_last_release
        run: |
          # TAG=$(gh release list \
          #   --json tagName,isPrerelease,isDraft,isLatest \
          #   --jq '[.[] | select(.isDraft == false and .isPrerelease == false and .isLatest == true)] | .[0].tagName')
          TAG=v0.1.3
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "Resolved TAG=$TAG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux:
    name: Building package documentation for Linux
    needs: resolve_tag
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Checkout tag
        run: |
          git checkout ${{ needs.resolve_tag.outputs.TAG }}
      # - name: Restore previously deployed docs
      #   run: |
      #     git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages-tmp || true
      #     cp -r gh-pages-tmp/* ./docs || true
      - name: DocC
        run: |
          rm -rf ./{{ needs.resolve_tag.outputs.TAG }} || true
          swift package --allow-writing-to-package-directory\
            generate-documentation \
            --target LoggerKit \
            --output-path ./${{ needs.resolve_tag.outputs.TAG }} \
            --transform-for-static-hosting \
            --disable-indexing \
            --hosting-base-path ${{ github.event.repository.name }}/linux/${{ needs.resolve_tag.outputs.TAG }}
          touch ./${{ needs.resolve_tag.outputs.TAG }}/.nojekyll
      - name: Archive site (Apple)
        run: tar -C ./${{ needs.resolve_tag.outputs.TAG }} -czf docs-linux.tar.gz .
      - uses: actions/upload-artifact@v4
        with:
          name: docs-linux
          path: docs-linux.tar.gz
  
  assemble_and_publish:
    name: Assemble & Publish gh-pages
    needs: [resolve_tag, build_linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: mkdir -p docs
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-linux
          path: .
      - name: Extract files
        run: |
          VER="${{ needs.resolve_tag.outputs.TAG }}"
          mkdir -p "docs/linux/${VER}"
          tar -xzf docs-linux.tar.gz -C "docs/linux/${VER}"
          # mkdir -p "docs/apple/${VER}"
          # tar -xzf docs-apple.tar.gz -C "docs/apple/${VER}"
      - name: Version sub-indexes
        run: |
          VER="${{ needs.resolve_tag.outputs.TAG }}"
          # echo '<meta http-equiv="refresh" content="0; url=./documentation/loggerkit/">' > "docs/apple/$VER/index.html"
          echo '<meta http-equiv="refresh" content="0; url=./documentation/loggerkit/">' > "docs/linux/$VER/index.html"
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          keep_files: true
          commit_message: tag-${{ needs.resolve_tag.outputs.TAG }}