name: Build documentation
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  docs:
    name: Building package documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Get previous stable release tag
        id: get_previous_release
        run: |
          TAG=$(gh release list --limit 100 \
            --json tagName,isPrerelease,isDraft \
            --jq '[.[] | select(.isDraft == false and .isPrerelease == false)] | .[1].tagName')

          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo $TAG
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Setup Swift
  #       uses: swift-actions/setup-swift@v2
  #       with:
  #         swift-version: 6
  #     - name: Swift-version
  #       run: swift --version
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ inputs.tag }}
  #     - name: Set up Pages
  #       uses: actions/configure-pages@v5
  #     - name: DocC
  #       run: swift package --allow-writing-to-package-directory generate-documentation --target LoggerKit --output-path ./docs/${{ inputs.tag }} --transform-for-static-hosting --disable-indexing --hosting-base-path LoggerKit/${{ inputs.tag }}
  #     - name: Update root file
  #       run: echo "<script>window.location.href += \"/documentation/loggerkit\"</script>" > docs/index.html
  #     - name: Copy version to latest
  #       run: cp -r ./docs/${{ inputs.tag }} ./docs/latest
  #     # - name: Upload artifacts
  #     #   uses: actions/upload-pages-artifact@v3
  #     #   with:
  #     #     path: ./docs
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v4
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./docs
  #         keep_files: true

  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: docs
  #   steps:
  #     - name: Deploy Docs
  #       uses: actions/deploy-pages@v4
