name: Test status for readme
on:
#  pull_request:
#    types: [opened, reopened, synchronize]
#    branches:
#      - 'master'
  - push
jobs:
  build-and-test:
    name: Test package with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.8", "6"]
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Swift-version
        run: swift --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: swift test
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
