name: Build package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - opened
    branches:
      - 'develop'
jobs:
  pr-test:
    name: Test package with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6"]
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Swift-version
        run: swift --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: swift test
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  #    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #    - name: Check out repository code
  #    uses: actions/checkout@v4
  #    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  #    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  #    - name: List files in the repository
  #    run: |
  #      ls ${{ github.workspace }}
  #    - run: echo "🍏 This job's status is ${{ job.status }}."

