name: Release
on:
  push:
    branches:
      - 'releases'
    # tags:
    #   - 'v*'
jobs:
  release:
    name: Building package documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch tags to local git
        run: |
          git fetch --tags --prune --unshallow || true
      - name: Extract previous tag
        id: get_previous_tag
        run: |
          PREV_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "PREVIOUS_TAG=$PREV_TAG" >> $GITHUB_OUTPUT
          echo $PREV_TAG
      - name: Generate Changelog from PRs (develop branch)
        id: changelog
        run: |
          PREV_TAG=${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}
          # CURR_TAG=${{ github.ref_name }}
          CURR_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)

          echo "🔁 Comparing: $PREV_TAG..$CURR_TAG"

          COMMITS=$(gh api repos/${{ github.repository }}/compare/$PREV_TAG...$CURR_TAG \
            --jq '.commits[].sha')
          echo $COMMITS

          # echo "## What's Changed" > RELEASE_CHANGELOG.md
          # echo "" >> RELEASE_CHANGELOG.md

          # for SHA in $COMMITS; do
          #   # PR_JSON=$(gh pr list --search "$SHA" --state merged --json number,title --jq '.[0]')
          #   PR_JSON=$(gh pr view $SHA --json number,title 2>/dev/null || true)
          #   if [ "$PR_JSON" != "null" ]; then
          #     # PR_TITLE=$(echo "$PR_JSON" | jq -r '.title')
          #     # PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          #     # echo "- $PR_TITLE (#$PR_NUMBER)" >> RELEASE_CHANGELOG.md
          #     echo "$PR_JSON" > RELEASE_CHANGELOG.md
          #     echo "" >> RELEASE_CHANGELOG.md
          #   fi
          # done

          # cat RELEASE_CHANGELOG.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}