name: Release
on:
  push:
    branches:
      - 'releases'
    # tags:
    #   - 'v*'
jobs:
  release:
    name: Building package documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch tags to local git
        run: |
          git fetch --tags --prune --unshallow || true
      - name: Extract previous tag
        id: get_previous_tag
        run: |
          PREV_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "PREVIOUS_TAG=$PREV_TAG" >> $GITHUB_OUTPUT
          echo $PREV_TAG
      - name: Generate Changelog from PRs (develop branch)
        id: changelog
        run: |
          PREV=${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}
          CURR=${{ github.ref_name }}

          echo "Previous tag: $PREV"
          echo "Current tag: $CURR"

          COMMITS=$(git log $PREV..$CURR --pretty=format:"%H")
          echo "Commits between $PREV and $CURR:"
          echo "$COMMITS"

          echo "PRs merged between tags:" > RELEASE_CHANGELOG.md

          for COMMIT in $COMMITS; do
            PR_NUMBER=$(gh pr list --search "$COMMIT" --state merged --json number,title --jq '.[0].number')
            PR_TITLE=$(gh pr list --search "$COMMIT" --state merged --json number,title --jq '.[0].title')
            if [ "$PR_NUMBER" != "null" ]; then
              echo "- $PR_TITLE (#$PR_NUMBER)" >> RELEASE_CHANGELOG.md
            fi
          done

          cat RELEASE_CHANGELOG.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}